### ISSUE TITLE
Emulator fails to correctly calculate some integer divisions

### ISSUE THREAD

**Issue by erwinbonsma** [aoneill01/gamebuino-emulator#7]
First of all, thanks a lot for making the emulator available. Much appreciated. I have been using it a lot.

Recently I started experimenting with the [Advanced Raycasting](https://gamebuino.com/creations/advanced-raycasting) library. The provided binaries run fine on both the Gamebuino and the emulator. However, when I build the code, I get artefacts when running it on the emulator.

My system:
* macOS 10.15.6
* Compiler: arm-none-eabi-gcc (GNU Tools for Arm Embedded Processors 7-2017-q4-major) 7.2.1 20170904 (release) [ARM/embedded-7-branch revision 255204]

For example:

![demo-new-emu](https://user-images.githubusercontent.com/37155479/94732946-48a1a500-0367-11eb-8630-b53835d2e04f.png)

When I upload it to the Gamebuino, it still runs fine. Interestingly, both the old and new (WASM-based) emulators fail, but with different artefacts.

![demo-old-emu](https://user-images.githubusercontent.com/37155479/94736082-f616b780-036b-11eb-89b6-f42459286fb8.png)

I managed to narrow down the problem to division results being occasionally incorrect. The code below reproduces the problem:

    #include <Gamebuino-Meta.h>

    typedef int32_t RCL_Unit;

    RCL_Unit dump1(RCL_Unit mul) {
      RCL_Unit v = -23998;
      RCL_Unit sum = 0;
  
      for (int i = 0; i < 3; i++) {
        RCL_Unit result = v / 80;

        gb.display.printf("%d/80=%d\n", v, result);
        sum += result * mul;
     
        v += 1;
      }

      return sum;
    }

    RCL_Unit dump2(RCL_Unit mul) {
      RCL_Unit vals[3] = { -23998, -23997, -23996 };
      RCL_Unit sum = 0;

      for (int i = 0; i < 3; i++) {
        RCL_Unit v = vals[i];
        RCL_Unit result = v / 80;

        gb.display.printf("%d/80=%d\n", v, result);
        sum += result * mul;
      }

      return sum;
    }

    void draw() {
      gb.display.setColor(0);
      gb.display.fillRect(0, 0, 80, 64);

      gb.display.setColor(WHITE);
      gb.display.setCursor(0, 0);

      RCL_Unit sum1 = dump1(1);
      RCL_Unit sum2 = dump2(1);
      gb.display.printf("%d, %d\n", sum1, sum2);
    }

    void setup() {
      gb.begin();
    }

    void loop() {
      while(!gb.update());
      draw();
    }

Both dump methods carry out the same integer divisions, and should produce the same output. (The sum calculations with a parameter-provided multiplication are there to ensure that the bug still occurs when the gb.display output in the dump methods is commented out. Without it, the compiler optimises the division code away). However, they do not on the binaries when I build the source: [bug-repro.bin.zip](https://github.com/aoneill01/gamebuino-emulator/files/5308050/bug-repro.bin.zip)

The output (in the emulator) is as follows:

![bug-repro](https://user-images.githubusercontent.com/37155479/94734055-ee094880-0368-11eb-8d88-3481bb617d03.png)

It shows that two of the divisions in the dump2 method give the incorrect results. My hypothesis is that the compiler on my system generates assembly code to implement division that uses instructions that are not (correctly) implemented by the emulator.

However, as I am not very familiar with ARM assembly code nor the emulator code, it's not clear to me how to investigate this further. Simply adding log statements to the emulator does not seem too promising, as I fear the execution of the code of interest gets lost in the execution of all the other (Gamebuino core library) instructions. Also, the continuous running of the update loop and not being able to pause execution also suggests a different debugging approach might be needed.

So, do you have any idea what the problem could be?
Do you have recommendations on how to proceed with investigating the problem? Any debugging tips?

**Comment by aoneill01** [comment]
@erwinbonsma - Wow, thanks for the detailed reproduction and analysis! Your hypothesis is likely correct. Just a wild guess, but maybe one of the instructions isn't correctly calculating an overflow or carry flag correctly, and the divide function depends on it.

It isn't easy to debug the emulator. For some similar bugs in the past I would:
1. decompile the game exhibiting the bug to ARM assembly. I can't remember the exact command I used, but the output included some comments showing function names from the original program.
2. find some addresses of functions I thought might be the problem
3. edit the emulator to halt or print info when it reached the addresses from (2)
4. step through the instructions, looking for anything that seems incorrect about the emulator state

You are welcome to try and debug it. Not sure when I would get around to it, but what you've provided will be a big help.

**Comment by erwinbonsma** [comment]
@aoneill01 - Thanks for your tips on how to debug. FYI, I have made some progress. I pretty much executed the four steps you suggested. Instead of stepping through the code, I traced the register state during the execution of the code of interest. So I now have traces of the code where I execute the divisions, as well as of the routine used to carry out the divisions.

In the tracing I can indeed see the results of the three divisions in the dump2 being respectively executed incorrectly, correctly, and incorrectly. As it turned out, the dump1 routine does not execute any divisions. Here the for-loop is unwound by the compiler with the results of the three divisions hard-coded in the binary.

The next step is to identify where in the division routine the emulator makes an error. Unfortunately, I do not have a reference trace, i.e. trace of the code where the same division(s) that go wrong in the emulator are executed correctly. So I either have to somehow generate that (from a different emulator, or execution on an actual Gamebuino?), or reverse-engineer/grok the division routine, and from that see where it goes wrong. Wish me luck! ;-)

**Comment by erwinbonsma** [comment]
I found the problem and managed to fix it. Expect a pull request sometime this weekend.

**Comment by aoneill01** [comment]
That is great news! Looking forward to the pull request.

**Comment by erwinbonsma** [comment]
The problem turned out to be caused by incorrect implementation of the shift instructions.

When building on my machine, it used the speed-optimised integer division routines from https://github.com/gcc-mirror/gcc/blob/master/libgcc/config/arm/lib1funcs.S
More specifically, the problem occurred when executing the code from the THUMB1_Div_Negative macro. It uses two shifts to determine the sign of the dividend and divisor, respectively LSR #31 and ASR #32. These often failed to give the correct results.

See my pull request for details of the problem and fix:
https://github.com/aoneill01/gamebuino-emulator/pull/8

**Comment by erwinbonsma** [comment]
Attached a Gamebuino binary of a "hello world" Raycast app that can be used to verify the fix (and to reproduce the problem).
[helloRay.bin.zip](https://github.com/aoneill01/gamebuino-emulator/files/5358697/helloRay.bin.zip)

**Comment by aoneill01** [comment]
Fixed by @erwinbonsma in #8
